### ISSUE TITLE
What is changed vs BabylonHx?

### ISSUE THREAD

**Issue by TiZ-EX1** [exaphaser/OmniHx3D#1]
Hiya. I can tell that this is a modified fork of BabylonHx, but I don't know *what* is different about it, or why I would use it over BHX. Please update the readme to indicate what is different.

**Comment by 0xFireball** [comment]
It adds relative mouse movement because I wanted the feature. This basically contains additonal things that I add but do not want to add to the main project

**Comment by TiZ-EX1** [comment]
That... that's all you added? And you don't want to make a pull request to the main project? Why not?

**Comment by 0xFireball** [comment]
There wasn't supposed to be much more. It was a repository for my own modifications that I did not want to pull. I'm simply keeping this as a snapshot that works, as I sometimes have issues with the original repository.

**Comment by TiZ-EX1** [comment]
That reasoning resonates more with me. BHX does tend to break a lot. Sorry to bother you.
